import java.io.File

/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.8/userguide/multi_project_builds.html in the Gradle documentation.
 */

pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
    id("de.fayard.refreshVersions") version "0.40.1"
}

rootProject.name = "coinchange"
include("app")

// Function to include all subprojects recursively
fun includeSubprojectsRecursively(dir: File) {
    dir.listFiles()?.forEach { file ->
        if (file.isDirectory) {
            val buildFile = File(file, "build.gradle.kts")
            if (buildFile.exists()) {
                include(file.relativeTo(rootDir).path.replace(File.separator, ":"))
            }
            includeSubprojectsRecursively(file)
        }
    }
}

// Start including subprojects from the root directory
includeSubprojectsRecursively(rootDir)